In [2]:
import pandas as pd
import sqlite3

df = pd.read_csv(r"C:\Users\ammar\OneDrive\Desktop\Sample - Superstore.csv" , encoding = 'latin1' )

#  Create a new SQLite database
conn = sqlite3.connect("superstore.db")

# Store the data in a table
df.to_sql("superstore", conn, if_exists="replace", index=False)

#  Verify the data
print("Rows inserted:", pd.read_sql("SELECT COUNT(*) AS total FROM superstore", conn))

Rows inserted:    total
0   9994

In [3]:
df.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

In [21]:
query_a = """
SELECT Region, Category, SUM(Sales) AS Total_Sales
FROM superstore
WHERE Sales > 0
GROUP BY Region, Category
ORDER BY Total_Sales DESC;
"""
pd.read_sql(query_a, conn)

     Region         Category  Total_Sales
0      East       Technology  264973.9810
1      West        Furniture  252612.7435
2      West       Technology  251991.8320
3      West  Office Supplies  220853.2490
4      East        Furniture  208291.2040
5      East  Office Supplies  205516.0550
6   Central       Technology  170416.3120
7   Central  Office Supplies  167026.4150
8   Central        Furniture  163797.1638
9     South       Technology  148771.9080
10    South  Office Supplies  125651.3130
11    South        Furniture  117298.6840

In [22]:
# Create a small lookup table for region manager names
region_managers = pd.DataFrame({
    "Region": ["East", "West", "Central", "South"],
    "Manager": ["Alice", "Bob", "Charlie", "Diana"]
})

region_managers.to_sql("region_managers", conn, if_exists="replace", index=False)

query_b = """
SELECT s.Region, s.Category, SUM(s.Sales) AS Total_Sales, r.Manager
FROM superstore s
LEFT JOIN region_managers r
ON s.Region = r.Region
GROUP BY s.Region;
"""
pd.read_sql(query_b, conn)

    Region         Category  Total_Sales  Manager
0  Central  Office Supplies  501239.8908  Charlie
1     East        Furniture  678781.2400    Alice
2    South        Furniture  391721.9050    Diana
3     West  Office Supplies  725457.8245      Bob

In [23]:
query_c = """
SELECT * FROM superstore
WHERE Sales > (SELECT AVG(Sales) FROM superstore);
"""
pd.read_sql(query_c, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2355,9974,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10004080,Technology,Phones,Avaya 5410 Digital phone,271.9600,5,0.20,27.1960
2356,9977,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980
2357,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152
2358,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
2359,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [25]:
query_c = """
SELECT * FROM superstore
WHERE Sales > (SELECT AVG(Sales) FROM superstore);
"""
pd.read_sql(query_c, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
3,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
4,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2355,9974,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10004080,Technology,Phones,Avaya 5410 Digital phone,271.9600,5,0.20,27.1960
2356,9977,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,TEC-PH-10002496,Technology,Phones,Cisco SPA301,249.5840,2,0.20,31.1980
2357,9980,US-2016-103674,12/6/2016,12/10/2016,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152
2358,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
2359,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [26]:
query_d = """
SELECT Category, SUM(Sales) AS Total_Sales, AVG(Profit) AS Avg_Profit
FROM superstore
GROUP BY Category;
"""
pd.read_sql(query_d, conn)

          Category  Total_Sales  Avg_Profit
0        Furniture  741999.7953    8.699327
1  Office Supplies  719047.0320   20.327050
2       Technology  836154.0330   78.752002

In [27]:
conn.execute("""
CREATE VIEW IF NOT EXISTS sales_summary AS
SELECT Region, Category, SUM(Sales) AS Total_Sales, SUM(Profit) AS Total_Profit
FROM superstore
GROUP BY Region, Category;
""")

# Check the view
pd.read_sql("SELECT * FROM sales_summary", conn)

     Region         Category  Total_Sales  Total_Profit
0   Central        Furniture  163797.1638    -2871.0494
1   Central  Office Supplies  167026.4150     8879.9799
2   Central       Technology  170416.3120    33697.4320
3      East        Furniture  208291.2040     3046.1658
4      East  Office Supplies  205516.0550    41014.5791
5      East       Technology  264973.9810    47462.0351
6     South        Furniture  117298.6840     6771.2061
7     South  Office Supplies  125651.3130    19986.3928
8     South       Technology  148771.9080    19991.8314
9      West        Furniture  252612.7435    11504.9503
10     West  Office Supplies  220853.2490    52609.8490
11     West       Technology  251991.8320    44303.6496

In [28]:
conn.execute("CREATE INDEX IF NOT EXISTS idx_region_category ON superstore (Region, Category);")